image: bioconductor/devel_core2
test:
  script:
    - R -e 'install.packages("testthat", repos="http://cran.mtu.edu")'
    - R -e 'BiocManager::install("BiocCheck")'
    - R CMD build .
    - R CMD check *tar.gz
    - R CMD BiocCheck *tar.gz
