---
title: "RSeqAn"
output:
  pdf_document:
    toc: yes
  html_notebook: default
  html_document: default
bibliography: paper.bib
---

Benchmarking

```{r}
library(RSeqAn)
devtools::install_github("compbiocore/qckitfastq", ref="v0.9-prerelease")
library(qckitfastq)
```

# Summary

This package provides R with access to SeqAn v2.4 [@Doring2008] header files. SeqAn is an open source C++ library of efficient algorithms and data structures for the analysis of sequences with a focus on biological data. Many packages in R are sped up with C or C++ code, but this is not a common practice in R packages for bioinformatics (back up this statement by an analysis of packages on Bioconductor). By providing access to SeqAn header files as well as wrappers to convert between R objects and C++ objects (look up exact terminology), we provide an easy way to write R bioinformatics packages that are much more efficient.

As a proof of concept for its utility, we have benchmarked a package that uses RSeqAn for quality control on bioinformatics data compared to other packages on Bioconductor that are written purely in R.

Statement of need

Benchmark

RSeqAn has been used in `qckitfastq` recently.

# References